parser: '@typescript-eslint/parser'
parserOptions:
  ecmaVersion: 2018
  sourceType: module
plugins:
  - '@typescript-eslint'
env:
  es6: true
  node: true
  mocha: true
extends:
  - 'eslint:recommended'
  - 'plugin:@typescript-eslint/recommended'
  - 'prettier'
  - 'prettier/@typescript-eslint'
globals:
  Atomics: readonly
  SharedArrayBuffer: readonly
rules:
  '@typescript-eslint/explicit-member-accessibility': off
  '@typescript-eslint/explicit-function-return-type': off
  '@typescript-eslint/camelcase': off
  '@typescript-eslint/no-parameter-properties': off
  '@typescript-eslint/no-explicit-any': off
  '@typescript-eslint/no-object-literal-type-assertion':
    [warn, { allowAsParameter: true }]
  'no-console': warn
