language: node_js
node_js:
  - 10.16.0

# https://docs.travis-ci.com/user/ci-environment/#Virtualization-environments
sudo: false

# https://blog.travis-ci.com/2013-12-05-speed-up-your-builds-cache-your-dependencies/
cache:
  yarn: true
  directories:
    - node_modules
    - '$HOME/.yarn-cache'

# https://docs.travis-ci.com/user/customizing-the-build#Git-Clone-Depth
git:
  depth: 1

# https://docs.travis-ci.com/user/customizing-the-build#Building-Specific-Branches
branches:
  only:
    - master
    - develop
    - /^release-.*$/
    - hotfixes
    - /^hotfix-.*$/
    - /^feature-.*$/

script:
  - yarn test
  - nyc report --reporter=json
  - codecov -f coverage/*.json
